### ISSUE TITLE
Exception in service when deploying vert.x + db + rest + WA

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-creator-backend#100]
```

Exception in thread "vert.x-eventloop-thread-0" java.sql.SQLSyntaxErrorException: Query was empty
--
  | at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
  | at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
  | at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  | at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:781)
  | at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
  | at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
  | at io.vertx.ext.jdbc.impl.actions.JDBCExecute.execute(JDBCExecute.java:46)
  | at io.vertx.ext.jdbc.impl.actions.JDBCExecute.execute(JDBCExecute.java:31)
  | at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:58)
  | at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$0(AbstractJDBCAction.java:66)
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
  | at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | java.sql.SQLSyntaxErrorException: Query was empty
  | at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
  | at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
  | at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  | at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:781)
  | at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
  | at com.mchange.v2.c3p0.impl.NewProxyStatement.execute(NewProxyStatement.java:75)
  | at io.vertx.ext.jdbc.impl.actions.JDBCExecute.execute(JDBCExecute.java:46)
  | at io.vertx.ext.jdbc.impl.actions.JDBCExecute.execute(JDBCExecute.java:31)
  | at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:58)
  | at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$0(AbstractJDBCAction.java:66)
  | at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
  | at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.lang.Thread.run(Thread.java:748)
  | Dec 05, 2018 3:56:33 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer


```

**Comment by quintesse** [comment]
Can you take a look at this @gastaldi ? :-)
