### ISSUE TITLE
Node apps won't boot

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-creator-backend#107]
Builds fine, but the container won't start up:

```
git version 2.9.3
--
  | Using Node.js version: v11.0.0
  | Environment:
  | DEV_MODE=false
  | NODE_ENV=production
  | DEBUG_PORT=5858
  | Running as user uid=1000210000(default) gid=0(root) groups=0(root),1000210000
  | Launching via npm...
  | npm info it worked if it ends with ok
  | npm info using npm@6.4.1
  | npm info using node@v11.0.0
  | npm info lifecycle demo-node-react-postgres@1.0.0~prestart: demo-node-react-postgres@1.0.0
  | npm info lifecycle demo-node-react-postgres@1.0.0~start: demo-node-react-postgres@1.0.0
  | > demo-node-react-postgres@1.0.0 start /opt/app-root/src
  | > node .
  | internal/modules/cjs/loader.js:589
  | throw err;
  | ^
  | Error: Cannot find module '/opt/app-root/src'
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
  | at Function.Module._load (internal/modules/cjs/loader.js:513:25)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
  | at startup (internal/bootstrap/node.js:303:19)
  | at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
  | npm info lifecycle demo-node-react-postgres@1.0.0~start: Failed to exec start script
  | npm ERR! code ELIFECYCLE
  | npm ERR! errno 1
  | npm ERR! demo-node-react-postgres@1.0.0 start: `node .`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the demo-node-react-postgres@1.0.0 start script.
  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  | npm timing npm Completed in 379ms
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /opt/app-root/src/.npm/_logs/2018-12-10T07_46_51_523Z-debug.log


```

**Comment by quintesse** [comment]
Can you take a (first) look at this @edewit ?

**Comment by quintesse** [comment]
Even the simplest "rest"-only project has this problem, both when using the Launcher and the CLI, so it's not related to any combination of capabilities or the way it's deployed.

**Comment by quintesse** [comment]
It even gives an error when using the ZIP and running locally:

```
$ npm install
npm WARN deprecated nsp@3.2.1: The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting
npm WARN deprecated spdx@0.5.2: see spdx-expression-parse, spdx-satisfies, &c.

> my-app@1.0.0 postinstall /tmp/xxx
> license-reporter report -s && license-reporter save -s --xml licenses.xml


> my-app@1.0.0 prepare /tmp/xxx
> echo 'To confirm CVE compliance, run "npm run security-check"' 

To confirm CVE compliance, run "npm run security-check"
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my-app@1.0.0 No repository field.

added 1184 packages from 486 contributors and audited 6383 packages in 14.964s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm start

> my-app@1.0.0 start /tmp/xxx
> node .

internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '/tmp/xxx'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tschotan/.npm/_logs/2018-12-10T10_08_53_830Z-debug.log
```

**Comment by ALRubinger** [comment]
https://github.com/fabric8-launcher/launcher-planning/issues/186 Duplicate filing; sorry

**Comment by quintesse** [comment]
Fixed by https://github.com/fabric8-launcher/launcher-creator-backend/pull/109

Thanks @edewit !
