### ISSUE TITLE
Quarkus app fails to start

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-creator-backend#165]
Quarkus app with rest + database, no frontend.

Created on the command line with `yarn -s apply /tmp/xxx --runtime quarkus ittest health rest database`, didn't test frontend UI.

This is the error in the logs:

```
2019-03-20 02:51:38,365 WARN  [com.arj.ats.common] (main) ARJUNA048002: Could not find configuration file, URL was: null
--
  | java.lang.RuntimeException: Unable to load the dataSource driver
  | at io.quarkus.agroal.runtime.AbstractDataSourceProducer.createDataSource(AbstractDataSourceProducer.java:92)
  | at io.quarkus.agroal.runtime.DataSourceProducer.createDefaultDataSource(Unknown Source)
  | at io.quarkus.agroal.runtime.DataSourceProducer_ProducerMethod_createDefaultDataSource_7c487e3ef869f878aa871e917c94f4d26d5d5c56_Bean.create(Unknown Source)
  | at io.quarkus.agroal.runtime.DataSourceProducer_ProducerMethod_createDefaultDataSource_7c487e3ef869f878aa871e917c94f4d26d5d5c56_Bean.create(Unknown Source)
  | at io.quarkus.arc.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:89)
  | at io.quarkus.arc.AbstractSharedContext.lambda$new$0(AbstractSharedContext.java:34)
  | at io.quarkus.arc.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:114)
  | at io.quarkus.arc.LazyValue.get(LazyValue.java:42)
  | at io.quarkus.arc.ComputingCache.getValue(ComputingCache.java:56)
  | at io.quarkus.arc.AbstractSharedContext.get(AbstractSharedContext.java:40)
  | at io.quarkus.agroal.runtime.DataSourceProducer_ProducerMethod_createDefaultDataSource_7c487e3ef869f878aa871e917c94f4d26d5d5c56_Bean.get(Unknown Source)
  | at io.quarkus.agroal.runtime.DataSourceProducer_ProducerMethod_createDefaultDataSource_7c487e3ef869f878aa871e917c94f4d26d5d5c56_Bean.get(Unknown Source)
  | at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:279)
  | at io.quarkus.arc.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:267)
  | at io.quarkus.arc.ArcContainerImpl.instance(ArcContainerImpl.java:131)
  | at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.injectDataSource(FastBootHibernatePersistenceProvider.java:275)
  | at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(FastBootHibernatePersistenceProvider.java:173)
  | at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:62)
  | at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
  | at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
  | at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:114)
  | at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:71)
  | at io.quarkus.hibernate.orm.runtime.HibernateOrmTemplate.startAllPersistenceUnits(HibernateOrmTemplate.java:88)


```

**Comment by gastaldi** [comment]
@quintesse :
- if you're running locally with H2, you need to rename the `src/main/resources/application-local.properties` to `src/main/resources/application.properties` before building
- If you want to use the Database you selected, you need to build with `-Popenshift` AND run the app with the following variables:
   - `-Dquarkus.datasource.url=`
   - `-Dquarkus.datasource.username=`
   - `-Dquarkus.datasource.password=`

**Comment by gastaldi** [comment]
The `application.properties` renaming should not be required in future Quarkus versions

**Comment by gastaldi** [comment]
@quintesse I have pushed a change that makes the `-Popenshift` the default option. I updated the comment above

**Comment by quintesse** [comment]
If you want we can change the build command in the `gap` script to always use the `-Popenshift` option? (assuming that doesn't affect any of the other runtime builds)

That way someone can run `mvn package` and get something that works without setting up a database and the `gap` script and the it tests will work too. wdyt?

**Comment by gastaldi** [comment]
@quintesse shouldn't be needed.. `-Popenshift` is now the default option.

**Comment by quintesse** [comment]
Fixed by adding `-Popenshift` to the `gap` script
