### ISSUE TITLE
Error: An error occurred: Request failed with status code 500

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-creator-backend#168]
Trying to download any app (tried with Quarkus) throws the following error in the console:

```

2019-03-20T18:29:59.913Z SERVER ERROR 500 { Error: Missing property: 'maven'
--
  | at validateRequired (/opt/app-root/src/dist/lib/core/info/index.js:57:23)
  | at validateProperty (/opt/app-root/src/dist/lib/core/info/index.js:121:5)
  | at validatePossibleObject (/opt/app-root/src/dist/lib/core/info/index.js:126:9)
  | at defs.forEach.def (/opt/app-root/src/dist/lib/core/info/index.js:153:29)
  | at Array.forEach (<anonymous>)
  | at Object.validate (/opt/app-root/src/dist/lib/core/info/index.js:153:14)
  | at applyCapability (/opt/app-root/src/dist/lib/core/deploy/index.js:243:12)
  | at acc.then (/opt/app-root/src/dist/lib/core/deploy/index.js:272:21) msg: 'Missing property: \'maven\'' }
 ```

**Comment by gastaldi** [comment]
Seems to be caused by https://github.com/fabric8-launcher/launcher-creator-backend/commit/02c59c008af7a4eef099f77c89ac47934032c991 or https://github.com/fabric8-launcher/launcher-creator-backend/commit/bad9fb71f03a4f9b8e63fc1fc77b5b1d5f0cb601

**Comment by gastaldi** [comment]
@quintesse I reverted the offending commit. Please cherry-pick it again if you need it
