### ISSUE TITLE
Failure deploying nodejs + db

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-creator-backend#99]
```

  | git version 2.9.3
-- | --
  | Using Node.js version: v11.0.0
  | Environment:
  | DEV_MODE=false
  | NODE_ENV=production
  | DEBUG_PORT=5858
  | Running as user uid=1010680000(default) gid=0(root) groups=0(root),1010680000
  | Launching via npm...
  | npm info it worked if it ends with ok
  | npm info using npm@6.4.1
  | npm info using node@v11.0.0
  | npm info lifecycle my-team-app@1.0.0~prestart: my-team-app@1.0.0
  | npm info lifecycle my-team-app@1.0.0~start: my-team-app@1.0.0
  |  
  | > my-team-app@1.0.0 start /opt/app-root/src
  | > node .
  |  
  | internal/modules/cjs/loader.js:589
  | throw err;
  | ^
  |  
  | Error: Cannot find module '/opt/app-root/src'
  | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
  | at Function.Module._load (internal/modules/cjs/loader.js:513:25)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
  | at startup (internal/bootstrap/node.js:303:19)
  | at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
  | npm info lifecycle my-team-app@1.0.0~start: Failed to exec start script
  | npm ERR! code ELIFECYCLE
  | npm ERR! errno 1
  | npm ERR! my-team-app@1.0.0 start: `node .`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the my-team-app@1.0.0 start script.
  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  | npm timing npm Completed in 212ms
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /opt/app-root/src/.npm/_logs/2018-12-05T15_49_23_493Z-debug.log


```

**Comment by quintesse** [comment]
This issue is probably a dup of https://github.com/fabric8-launcher/launcher-creator-backend/issues/107 which is now fixed. Can you test, confirm and close @ia3andy ?

**Comment by gastaldi** [comment]
Fixed by fabric8-launcher/launcher-creator-backend#109, closing.

**Comment by quintesse** [comment]
Did you test it? ;-)
